### ISSUE TITLE
Where is Light.xaml or Dark.xaml located?

### ISSUE THREAD

**Issue by SwaroopSomanna** [benruehl/adonis-ui#136]
I've installed AdonisUI in my wpf application using nuget. Now I want to create a custom theme and store it in a file (CustomTheme.xaml). I need to copy contents from either Light.xaml or Dark.xaml and paste it into CustomTheme.xaml. But I'm unable to find Light.xaml or Dark.xaml in my project location. Can anyone please let me know where these files are by default stored inside the project folder?

**Comment by benruehl** [comment]
If you want to create a custom color scheme please refer to the respective [Adonis UI docs](https://benruehl.github.io/adonis-ui/docs/guides/colors-and-brushes/#custom-color-schemes).

If you want to look at the files you specified please have a look at the [repository files](https://github.com/benruehl/adonis-ui/tree/master/src/AdonisUI/ColorSchemes).

The files are not displayed because a NuGet package contains the compiled assemblies instead of the original source files. When including it in your project you won't see any new source files in your solution explorer but only the package reference.
This is better described in the [NuGet docs](https://docs.microsoft.com/en-us/nuget/what-is-nuget).
