### ISSUE TITLE
ZenTimings

### ISSUE THREAD

**Issue by irusanov** [benruehl/adonis-ui#138]
Hello again,

I'm using your AdonisUI for my memory timings tool dedicated to AMD Ryzen platform.
Some parts of the source code are a bit lame, but still working fine and my users really like the dark mode.

I would suggest adding it to the Expo, if you feel it is a worthy addition.

The site is: https://zentimings.protonrom.com/
Github: https://github.com/irusanov/ZenTimings

Thank you for the nice framework.

**Comment by benruehl** [comment]
Hi,

thanks for the suggestion. I'd love to add it to the Expo!
I'd go with the following metadata:

```
name: ZenTimings
author: Ivan Rusanov
tagline: A free, simple and lightweight app for monitoring memory timings on Ryzen platform.
project_url: https://zentimings.protonrom.com/
```

Is that okay? Please tell me if you prefer to have your GitHub user name displayed or the GitHub project URL instead of the website.

May I use [this image](https://github.com/irusanov/ZenTimings/issues/5) in addition to the image on your website for showing both themes?

**Comment by irusanov** [comment]
It looks fine.
I prefer my real name, but the github one is ok too. Whatever you choose.
As for the project url, let's change it to the github repo, since all the rest of projects on the Expo page have that.
The github repo and the site are connected with links anyway.

You can use that screenshot of the app, yes. I can also provide you with screenshots from the released version if required.

Thanks!
