### ISSUE TITLE
how to use in vb.net project.

### ISSUE THREAD

**Issue by omertrans678** [benruehl/adonis-ui#156]
How to use Adonis UI theme in VB.NET Project? no found app.xml have app.config

Thanks.

**Comment by JajinderK** [comment]
Hello OmerTrans678,
This is for a WPF application (XAML), not for standard WinForms.

**Comment by omertrans678** [comment]
Oh ok thanks. I want to ask questions

I created a new .Net Framework WPF project. I added NuGet and theme. Theme works. How to change togglebutton in button? I could not find guiding document

**Comment by benruehl** [comment]
Could you please elaborate what exaclty you mean with "How to change togglebutton in button?"? Do you mean how to change their appearances?

**Comment by tizu69** [comment]
> How to change togglebutton in button?

If you want to create a ToggleButton, use `<ToggleButton />` Instead of your standard `<Button />`.
If you want to have the normal Button with the style of a toggled ToggleButton, check out the `AccentButton` style as seen [here](https://benruehl.github.io/adonis-ui/docs/guides/styles-and-templates/#available-styles).

**Comment by omertrans678** [comment]
Thank you for information.
