### ISSUE TITLE
How to use StyleTriggers with Adonis?

### ISSUE THREAD

**Issue by Morasiu** [benruehl/adonis-ui#157]
Hello

I have a simple button like this. 

![image](https://user-images.githubusercontent.com/19236279/115610546-4b56ee00-a2e9-11eb-9011-9d8d8b0dd6f9.png)

But when I apply some style Trigger it breaks!

![image](https://user-images.githubusercontent.com/19236279/115610653-75a8ab80-a2e9-11eb-8cdc-c7072261ac4a.png)

> It's white icon on white background

My code:
```
<Button Name="PauseButton" Margin="10 0 0 0" MaxHeight="15" MaxWidth="30"
                      Grid.Column="9" Grid.Row="0" Padding="3">
                <Image Source="Assets\play.png" />
                <Button.Style>
                    <Style>
                        <Style.Triggers>
                            <DataTrigger Binding="{Binding IsIgnored}" Value="True">
                                <Setter Property="Button.IsEnabled" Value="False" />
                            </DataTrigger>
                    </Style>
                </Button.Style>
        </Button>
```

> NOTE: I have a default setup for Dark theme on Adonis

How can I properly use Adonis with `Style Triggers`?

**Comment by benruehl** [comment]
By setting a style like this your are throwing away Adonis UI's default style and the system fallback gets used instead. In order to add to Adonis UI's default style you need to base your style on it:

```xml
<Button.Style>
    <Style BasedOn="{StaticResource {x:Type Button}}">
    </Style>
</Button.Style>
```

For further information see for example [this stackoverflow thread](https://stackoverflow.com/questions/11581475/inherit-style-from-default-style).

On a personal note, it seems that you only want to set the button's `IsEnabled` property. This can be achieved without creating a style much easier:

```xml
<Button IsEnabled="{Binding IsIgnored, Converter={StaticResource InverseBooleanConverter}}"/>
```

You can create the converter on your own or use one of many libraries that offer those.
See [this stackoverflow thread](https://stackoverflow.com/questions/1039636/how-to-bind-inverse-boolean-properties-in-wpf) or make use of [NKristek.Wpf.Converters](https://www.nuget.org/packages/NKristek.Wpf.Converters/) or [Kent.Boogaart.Converters](https://www.nuget.org/packages/Kent.Boogaart.Converters/) for example.
