### ISSUE TITLE
Style for bottom right corner in ScrollView is missing

### ISSUE THREAD

**Issue by Thimilius** [benruehl/adonis-ui#23]
I encounterd a missing styling in the ScrollView that is inside a TextBox.

The corner rectangle in the bottom right that fills the space for both the vertical and horizontal scrollbar is tinted white in dark mode:
![ScrollView_Bug](https://user-images.githubusercontent.com/26960721/57039520-1d3ff580-6c5d-11e9-81e5-7d3baf5beffa.png)

There sort of is a workaround as it is possible to override this style with the following code:
```csharp
<TextBox>
    <TextBox.Resources>
        <SolidColorBrush x:Key="{x:Static SystemColors.ControlBrushKey}" Color="{DynamicResource {x:Static adonisUi:Colors.Layer2BackgroundColor}}"/>
    </TextBox.Resources>
</TextBox>
```
Resulting into the following:
![ScrollView_Workaround](https://user-images.githubusercontent.com/26960721/57039820-fb933e00-6c5d-11e9-858b-7a78ca9833bd.png)

But unfortunatley this overridden color does not match the background gradient of the TextBox that is present for the first 100 pixels or so.
(The color difference might be hard to notice in the images)

**Comment by benruehl** [comment]
Thank you for reporting this!
I will have a look at it as soon as I can.

**Comment by Atulin** [comment]
Has this been merged into master? I'm having the issue as well:
![image](https://user-images.githubusercontent.com/11233299/59945485-0c934b00-9468-11e9-9109-9f7deb3e7d61.png)
Using AdonisUI 1.10.0

**Comment by benruehl** [comment]
It is merged and should be fixed in the latest version on NuGet as well ([v1.11.0-preview](https://www.nuget.org/packages/AdonisUI.ClassicTheme/1.11.0-preview1)).

PS:
A stable version is following in a few days I hope. I released it as a preview because the NuGet packaging changed in this release because of .NET Core 3.0 and I wanted to be careful to not break anything. But as everything seems to work fine for everyone and my personal tests passed as well, I will probably just make the current release a stable one without changing anything. So the preview can be used relatively safely.

**Comment by Atulin** [comment]
Glad to hear, I'm not in a hurry with the release so I'll wait for it to go to master. Thanks!
