### ISSUE TITLE
Add style to titlebar

### ISSUE THREAD

**Issue by micah686** [benruehl/adonis-ui#24]
I would like the titlebar to have the style applied to it as well. It looks a little bit out of place when using the dark theme and having the white titlebar. I was thinking along the lines of how ModernUI did their [titlebar](https://camo.githubusercontent.com/19e7273bd317fe39b49c1d187884082e15c7ce33/687474703a2f2f6669727374666c6f6f72736f6674776172652e636f6d2f6d656469612f6769746875622f6d75692f6d75692e696e74726f2e706e67).

**Comment by benruehl** [comment]
Absolutely! This is already on my to-do list right after the .NET Core 3.0 support.

**Comment by micah686** [comment]
It looks like this issue has been fixed with/after the net core 3.0 addition.

**Comment by benruehl** [comment]
This is the major part of the 1.12 release (.NET Core support was v1.11). It is merged into the master already and available via NuGet as pre-release [1.12.0-preview2](https://www.nuget.org/packages/AdonisUI.ClassicTheme/1.12.0-preview2).

I did not close this issue because I am still testing if it works fine on different versions of Windows, different screen resolutions and different UI scalings. But it's fine to close it as well. Additionally, it is still missing documentation.

I am optimistic to finish it very soon, though.
