### ISSUE TITLE
Cannot find Dimensions.HorizontalSpace resource.

### ISSUE THREAD

**Issue by rasyidf** [benruehl/adonis-ui#25]
**Describe the bug**
A  **_Cannot find Dimensions.HorizontalSpace resource._** Error occur when adding Adonis to project,
 
**To Reproduce**
1. Create New WPF Project
2. Add Adonis Resource
3. Rebuild

**Expected behavior**
The Program Run normally but the error is annoying.

**Screenshots**
![image](https://user-images.githubusercontent.com/28984914/57965615-c92d5480-7970-11e9-8a4e-5cccae25b53a.png)

**Additional context**
Run using VS 2019 (16.1 Preview 3)

**Comment by benruehl** [comment]
Thank you for pointing this out.
I noticed this as well but wasn't able to track it down so far. It seems to be raised by the Xaml designer because it never shows up when I disable the designer. But even then it appears quite randomly for me. Sometimes it is shown, other times it is not.
I will see if I can find the source of the error.

**Comment by rasyidf** [comment]
I've fund out that it is some visual studio behavior, 
Shown in this
[KB](https://support.microsoft.com/en-us/help/4057582/xaml-wpf-designer-can-not-find-resource-keys-in-vs2017)

**Comment by benruehl** [comment]
So I am closing this now as it seems to be an issue with the Visual Studio Designer and not the library.

**Comment by osnapitzjamie** [comment]
is this still not resolved? This thing is unusable because of it...

**Comment by benruehl** [comment]
@osnapitzjamie have you even read the conversation?

As @rasyidf found out it is an [issue of the Visual Studio Designer](https://support.microsoft.com/en-us/help/4057582/xaml-wpf-designer-can-not-find-resource-keys-in-vs2017).
The bug report clearly states:
> Microsoft has confirmed that this is a problem in the Microsoft products that are listed in the "Applies to" section.

To fix it, you can try to perform the steps listed in the "Resolution" section of the bug report. Alternatively, you can simply deactivate the XAML designer completely.

As a side note, I think speaking of "unusable" is a slight exaggeration here. It is only a design time error which appears more or less randomly. I agree that it might disturb development because it may trigger a developer's OCD. But still, it is only a false positive error that does not stop anyone from building an application with the library. It even disappears during runtime.

In case you want to dig into this yourself, please feel free to contribute a fix.
