### ISSUE TITLE
Honor Windows text scaling

### ISSUE THREAD

**Issue by Bert-Proesmans** [benruehl/adonis-ui#39]
Since we now have an Adonis Window it would be great if it followed the text scaling settings of Windows. This would help people with large resolutions and could help find style bugs.
A cursory search yielded https://docs.microsoft.com/en-us/windows/win32/hidpi/declaring-managed-apps-dpi-aware, which also links to demo code.

Of course, if nobody wants to tackle the feature i'll get myself to it eventually.

**Comment by msmshazan** [comment]
Here's a Microsoft Sample for enabling per monitor DPI awareness https://github.com/Microsoft/WPF-Samples/tree/master/PerMonitorDPI

**Comment by benruehl** [comment]
As @msmshazan suggested it is only a setting in the `app.manifest` file required in order to support Windows' per monitor DPI awareness. The current version of the Adonis UI demo app shows how it can be done.

Closing this as it is not the responsibility of this library but of the client application instead.
