### ISSUE TITLE
Not all controls take on the Adonis style

### ISSUE THREAD

**Issue by Bert-Proesmans** [benruehl/adonis-ui#46]
Since the DataGrid styling has been merged i attempted to integrate adonis into my WPF program. The program makes extensive use of ContentControls, i also created my own to abstract adorned behaviour like a loading overlay etc.

I'm having issues with applying the datagrid style. I see controls like textboxes, checkboxes and scrollbars around and inside the DataGrid being styled, but the column row header, grid row header, grid row and spotlight are not being styled as expected.
I experimented further and placing the grid directly into the ShellView (Window object) doesn't fix it either. The grid styling just works within the Adonis Demo project, even with control relocations and other manipulations. I have no idea what else i could try.

My window currently looks like this; 
![image](https://user-images.githubusercontent.com/2027877/71417243-982ea400-2664-11ea-915c-83af89c22c74.png)

Do you happen to know what i could do to debug this?
Thank you in advance

**Comment by benruehl** [comment]
If I understood you correctly, you added AdonisUI to your project via NuGet and expected your DataGrid to be styled. But instead, it still looks like the default one.

The reason for this is that there is still no new release published to NuGet which includes the merged DataGrid styles. The latest release is like two months old.
But I can create a release if you like :)

This is not the reason for your issue in case you added AdonisUI directly from GitHub instead of NuGet of course.

**Comment by benruehl** [comment]
I created a release v1.13.0 and published it to NuGet which you can use now.

**Comment by Bert-Proesmans** [comment]
You are correct. I didn't properly verify what i was doing.
Apologies for the misunderstanding and thank you for the new release!
