### ISSUE TITLE
Suggestion - Provide an alternative Toolbar Button look

### ISSUE THREAD

**Issue by Swiftpaws** [benruehl/adonis-ui#61]
The toolbar button mouse over effect currently is barely noticeable.

I think that the style of the default button could be used to create an improved style.
Basically all that needs to be done is to clone the default button style and set the border brush to transparent.

If you have many buttons side by side (especially with icons as content) this just looks better imo.

**Comment by benruehl** [comment]
Thanks for your feedback.

I think you mean the toolbar button on layer 1 while having the light color scheme active. This one bothers me, too. But fortunately, it is the only combination that is barely visible, I think.

The good thing is that normally you'd have such a toolbar button inside some toolbar. This toolbar can have a background so that the issue is gone. Look at the left panel in the demo app, those are toolbar buttons as well and it is not an issue over there.

Maybe it was a bad idea to place the toolbar button in the demo at this spot. Because in my opinion it should not be placed on the base background like that without having some kind of toolbar around it. I simply wanted to present it on the front page because I think it has many uses and people should know it exists.

If you prefer the default button without a border thats totally fine. You can also remove the border globally from all controls via [Dimensions.BorderThickness](https://benruehl.github.io/adonis-ui/docs/guides/dimensions/) if you want a more flat look.

For now, I'd like to keep the current behavior. The transparent background is the most important difference between the toolbar button and the default button. That is also what is stated in the [docs](https://benruehl.github.io/adonis-ui/docs/guides/styles-and-templates/#available-styles) so people might rely on this. And I don't like to change this aspect for only a single imperfect constellation. Although I'd really like to see this issue solved as well.

Hope that's ok for you.
