### ISSUE TITLE
MessageBox missing, Update: Possibly misleading documentation

### ISSUE THREAD

**Issue by Lolle2000la** [benruehl/adonis-ui#74]
**Describe the bug**
After reading the documentation, I set out to try and integrate the `MessageBox` with my application. However I could not find it anywhere in the nuget package. `AdonisUI.Controls.MessageBox.Show` is nowhere to be found.

**To Reproduce**
1. Add `MessageBox.Show`
2. Add `using AdonisUI.Controls;`

**Expected behavior**
The program compiles and a message box will be shown

**Screenshots**

**Additional context**
I'm running on .NET Core 3.1.

**Comment by Lolle2000la** [comment]
Ok, I just noticed that it isn't in yet and comes in v1.14.0. No offense, but until then, maybe put in a disclaimer. It sure catched me off guard!

**Comment by benruehl** [comment]
Yeah that's an issue with all changes I do to documentation. Unfortunately, it cannot handle different versions of the library so I have to decide whether to have the docs on the state of the master branch or the last NuGet release. I feel like it is misleading whatever I choose.

But adding some kind of tag might be a good option for future cases, so thanks for the feedback. I think I will leave this particular page as it is for now because the release 1.14 is so close. I hope to finish it by this week.
