### ISSUE TITLE
AdonisWindows Titlebar too narrow

### ISSUE THREAD

**Issue by rasyidf** [benruehl/adonis-ui#81]
**Describe the bug**
when windows is maximized the title bar height shrink into 21pixels, even if it's normal behavior. consider adding option to keep the height. i. e. when merging menu with the titlebar

**To Reproduce**
Easiest step is opening adonisUI demo:
1. Open adonisUI.Demo
2. Maximize the window

**Expected behavior**
this is the visual studio code behavior
![image](https://user-images.githubusercontent.com/28984914/77252399-34793e80-6c86-11ea-801c-74b21882aec2.png)

**Screenshots**
This is the adonisUI.demo behavior
![image](https://user-images.githubusercontent.com/28984914/77252481-a3ef2e00-6c86-11ea-8c68-b4185bf02919.png)

**Additional context**
none

**Comment by rasyidf** [comment]
It seems it can be referred as suggestion rather than bug,

**Comment by benruehl** [comment]
As you already mentioned, I wouldn't call it a bug because it behaves just like expected.
`AdonisWindow` tries to mimic the default native window of Windows. Its title bar shrinks a little because so it does for native applications like the Windows Explorer or Power Shell or even any WPF app without styling.

VS Code behaves differently because it ueses its own implementation. But in my opinion this should not be the default for a UI library because VS Code is just a single app like any other and not some kind of standard.

Adding an option to keep the height might be a good idea though.

In the meantime, you can achive this by performing the following steps:

1. Copy the [`WindowButton.xaml`](https://github.com/benruehl/adonis-ui/blob/master/src/AdonisUI.ClassicTheme/NamedStyles/WindowButton.xaml) file to your application
2. Remove the following `DataTrigger` from your copy
   ```xml
   <DataTrigger Binding="{Binding WindowState, RelativeSource={RelativeSource FindAncestor, AncestorType=Window}}" Value="Maximized">
       <Setter Property="Height" Value="22"/>
   </DataTrigger>
   ```
3. Include the file **below** the resources of Adonis UI, e.g.:
   ```xml
   <Application.Resources>
       <ResourceDictionary>
           <ResourceDictionary.MergedDictionaries>
               <ResourceDictionary Source="pack://application:,,,/AdonisUI;component/ColorSchemes/Light.xaml"/>
               <ResourceDictionary Source="pack://application:,,,/AdonisUI.ClassicTheme;component/Resources.xaml"/>
               <ResourceDictionary Source="../WindowButton.xaml"/>
           </ResourceDictionary.MergedDictionaries>
       </ResourceDictionary>
   </Application.Resources>
   ```

Hope this helps :)

**Comment by rasyidf** [comment]
Thanks for the response, it helps a lot.

**Comment by rabbit59** [comment]
I thought I would add my voice to the titlebar size.  If you are going to add a menu and/or buttons to the titlebar you actually need the height to remain the same when maxmized so you get a nice aesthetic look, otherwise it looks cramped.  A property to control this would be great.  

(BTW great product and is there an online community?).

**Comment by benruehl** [comment]
@rabbit59 Thanks for sharing your opinion.
Seems like this would be beneficial for multiple people now, so I will prioritize this when working on the next update.
