### ISSUE TITLE
Hide window title bar options

### ISSUE THREAD

**Issue by joaosigma** [benruehl/adonis-ui#99]
I would like to be able to create a _simple_ window, where the user is able to input simple commands. The keep the design of the window also simple, I would like to be able to hide the window title bar.

I think a simple property like "HideTitleBar" in AdonisWindow would be great.

**Comment by benruehl** [comment]
Do you mean you want to toggle the visibility of the title bar and possibly want to animate the process of appearing and disappearing?

Because if not, you can always just use the default `Window` and set its `WindowStyle` to `None`. The custom title bar is the only feature of `AdonisWindow` that makes it different from `Window`. If you don't want the title bar just don't use it I guess.

Or did I misunderstand you?

**Comment by joaosigma** [comment]
Sorry for the late response.

I meant the visibility.

I tried to set the `WindowStyle` to `None` but it didn't work when using `AdonisWindow` (which probably should for consistency?). There are other stuff that using `AdonisWindow` will automatically set, like Style, which is why I would like to use it in all my windows (even if not using it for its main feature).
